language: go

install:
  - go get github.com/sourcegraph/lsif-go/cmd/lsif-go
  - curl -L https://github.com/sourcegraph/src-cli/releases/download/3.16.0/src_linux_amd64 -o ./src
  - chmod +x ./src

jobs:
  include:
    - name: Index and upload LSIF data to sourcegraph.com
      os: linux 
      go: 1.14.x
      script:
        - go get -t -v -d ./...
        - go mod vendor
        - lsif-go
        - ./src lsif upload -no-progress
